# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: archivo.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'archivo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rarchivo.proto\";\n\x10OperationRequest\x12\t\n\x01\x61\x18\x01 \x01(\x02\x12\t\n\x01\x62\x18\x02 \x01(\x02\x12\x11\n\toperation\x18\x03 \x01(\t\"#\n\x11OperationResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\x32?\n\x0b\x43\x61lculation\x12\x30\n\x07\x43ompute\x12\x11.OperationRequest\x1a\x12.OperationResponse2F\n\tOperation\x12\x39\n\x10PerformOperation\x12\x11.OperationRequest\x1a\x12.OperationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'archivo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERATIONREQUEST']._serialized_start=17
  _globals['_OPERATIONREQUEST']._serialized_end=76
  _globals['_OPERATIONRESPONSE']._serialized_start=78
  _globals['_OPERATIONRESPONSE']._serialized_end=113
  _globals['_CALCULATION']._serialized_start=115
  _globals['_CALCULATION']._serialized_end=178
  _globals['_OPERATION']._serialized_start=180
  _globals['_OPERATION']._serialized_end=250
# @@protoc_insertion_point(module_scope)
